spring:
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

   jpa:
     hibernate:
      ddl-auto: update
    
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

   application:
      name: Tracker-service
   config:
    activate:
      on-profile:
      - "test"
server:
  port: 4045      




---

spring:
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

   jpa:
     hibernate:
      ddl-auto: update
    
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

   application:
      name: Tracker-service
   config:
    activate:
      on-profile:
      - "dev"
server:
  port: 8085      




